name: Build

on:
   - push
   - pull_request

defaults:
   run:
     shell: bash
     # working-directory: src

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.21.0'
      - run: echo $HOME
      - run: echo $GOCACHE
      - run: echo $XDC_CACHE_HOME
